* configure.in, configure: add PACKAGE_PATCHLEVEL of 3.0.1 with 	package version at 3.0.  Add recogition for Aqua configure. 	Make use of SHLIB_SUFFIX var.

diff --git a/tclplugin/configure b/tclplugin/configure
--- a/tclplugin/configure
+++ b/tclplugin/configure
@@ -1317,6 +1317,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+cat >>confdefs.h <<\_ACEOF
+#define PACKAGE_PATCHLEVEL "3.0.1"
+_ACEOF
+
 
 ac_aux_dir=
 for ac_dir in tclconfig $srcdir/tclconfig; do
@@ -11649,12 +11653,13 @@ _ACEOF
 
 
 
-if test "${TEA_PLATFORM}" = "windows" ; then
-    cat >>confdefs.h <<_ACEOF
+case "${TEA_WINDOWINGSYSTEM}" in
+    win32)
+	cat >>confdefs.h <<_ACEOF
 #define BUILD_nptcl 1
 _ACEOF
 
-    CLEANFILES="pkgIndex.tcl *.lib *.dll *.exp *.ilk *.pdb *.pch"
+	CLEANFILES="pkgIndex.tcl *.lib *.dll *.exp *.ilk *.pdb *.pch"
 
     vars="\$(WIN_OBJECTS)"
     for i in $vars; do
@@ -11700,36 +11705,107 @@ echo "$as_me: error: could not find source file '$i'" >&2;}
     done
 
 
-    cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define XP_WIN 1
 _ACEOF
 
-    cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define _WINDOWS 1
 _ACEOF
 
-    cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define _WIN32 1
 _ACEOF
 
-    cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define WIN32_LEAN_AND_MEAN 1
 _ACEOF
 
-    # We could do this with a .def file, but this is a bit easier
-    # These functions need exporting, but they are part of the NPAPI that
-    # has some strict declarations that you don't want to play with.
-    SHLIB_LD="${SHLIB_LD} -export:NP_GetEntryPoints,@1"
-    SHLIB_LD="${SHLIB_LD} -export:NP_Initialize,@2"
-    SHLIB_LD="${SHLIB_LD} -export:NP_Shutdown,@3"
-    LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/bin
-    TCL_LIB_FILE=${TCL_DLL_FILE}
-else
-    cat >>confdefs.h <<\_ACEOF
+	# We could do this with a .def file, but this is a bit easier
+	# These functions need exporting, but they are part of the NPAPI that
+	# has some strict declarations that you don't want to play with.
+	SHLIB_LD="${SHLIB_LD} -export:NP_GetEntryPoints,@1"
+	SHLIB_LD="${SHLIB_LD} -export:NP_Initialize,@2"
+	SHLIB_LD="${SHLIB_LD} -export:NP_Shutdown,@3"
+	LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/bin
+	TCL_LIB_FILE=${TCL_DLL_FILE}
+	;;
+    aqua)
+	cat >>confdefs.h <<\_ACEOF
+#define XP_MACOSX 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define MAC_TCL 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define MAC_OSX_TCL 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define MAC_OSX_TK 1
+_ACEOF
+
+
+    vars="-I${TK_TOP_DIR_NATIVE}/macosx"
+    for i in $vars; do
+	PKG_INCLUDES="$PKG_INCLUDES $i"
+    done
+
+
+
+    vars="-framework Carbon"
+    for i in $vars; do
+	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
+	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
+	    i=`echo "$i" | sed -e 's/^\([^-].*\)\.lib$/-l\1/i'`
+	fi
+	PKG_LIBS="$PKG_LIBS $i"
+    done
+
+
+
+    vars="\$(MACOSX_OBJECTS)"
+    for i in $vars; do
+	case $i in
+	    \$*)
+		# allow $-var names
+		PKG_SOURCES="$PKG_SOURCES $i"
+		PKG_OBJECTS="$PKG_OBJECTS $i"
+		;;
+	    *)
+		# check for existence - allows for generic/win/unix VPATH
+		if test ! -f "${srcdir}/$i" -a ! -f "${srcdir}/generic/$i" \
+		    -a ! -f "${srcdir}/win/$i" -a ! -f "${srcdir}/unix/$i" \
+		    ; then
+		    { { echo "$as_me:$LINENO: error: could not find source file '$i'" >&5
+echo "$as_me: error: could not find source file '$i'" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+		PKG_SOURCES="$PKG_SOURCES $i"
+		# this assumes it is in a VPATH dir
+		i=`basename $i`
+		# handle user calling this before or after TEA_SETUP_COMPILER
+		if test x"${OBJEXT}" != x ; then
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.${OBJEXT}"
+		else
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.\${OBJEXT}"
+		fi
+		PKG_OBJECTS="$PKG_OBJECTS $j"
+		;;
+	esac
+    done
+
+
+
+	;;
+    x11)
+	cat >>confdefs.h <<\_ACEOF
 #define XP_UNIX 1
 _ACEOF
 
-    CLEANFILES="pkgIndex.tcl"
+	CLEANFILES="pkgIndex.tcl"
 
     vars="\$(UNIX_OBJECTS)"
     for i in $vars; do
@@ -11764,14 +11840,26 @@ echo "$as_me: error: could not find source file '$i'" >&2;}
 
 
 
-    TCL_LIB_FILE=${TCL_LIB_FILE}
-    # This should enable us to have the TCL_LIB_FILE located at runtime
-    # with the -R path ... might not be necessary.
-    LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/lib
-    SHLIB_LD="${SHLIB_LD} ${LD_SEARCH_FLAGS}"
-fi
+	TCL_LIB_FILE=${TCL_LIB_FILE}
+	# This should enable us to have the TCL_LIB_FILE located at runtime
+	# with the -R path ... might not be necessary.
+	LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/lib
+	SHLIB_LD="${SHLIB_LD} ${LD_SEARCH_FLAGS}"
+	;;
+    *)
+	{ { echo "$as_me:$LINENO: error: Unknown TEA_WINDOWINGSYSTEM \"${TEA_WINDOWINGSYSTEM}\"" >&5
+echo "$as_me: error: Unknown TEA_WINDOWINGSYSTEM \"${TEA_WINDOWINGSYSTEM}\"" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+esac
 
 
+
+
+
+cat >>confdefs.h <<_ACEOF
+#define SHLIB_SUFFIX "${SHLIB_SUFFIX}"
+_ACEOF
 
 
 
